import PropTypes from 'prop-types';
import { Inter } from 'next/font/google';
import Script from 'next/script'; // Correct import
import { ThemeProvider } from 'next-themes';
import './globals.css';
import { Providers } from './providers'; // Import the Providers wrapper

import Navbar from '@/components/Navbar';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <head>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
    </head>
    <body className={inter.className}>
      <Providers> 
        <Navbar />
        <main>{children}</main>
      </Providers>
      <Script rel="preload" as="font" src="https://kit.fontawesome.com/269c8a4f7b.js" crossorigin="anonymous" strategy="beforeInteractive" />
    </body>
  </html>
);

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};

export default RootLayout;
